app:
  dashboard_url: "http://5.161.105.106:3001" # REPLACE WITH YOUR DOMAIN OR IP

domains:
  domain1:
    base_domain: "pangolin.t99ltd.com" # REPLACE WITH YOUR DOMAIN OR IP
    cert_resolver: "letsencrypt" 

server:
  secret: "your-strong-secret"

gerbil:
  base_endpoint: "pangolin.t99ltd.com" # REPLACE WITH YOUR DOMAIN OR IP

flags:
  require_email_verification: false
  disable_signup_without_invite: true
  disable_user_create_org: true